server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Angular routing için hayat kurtaran satır:
        try_files $uri $uri/ /index.html; 
    }
}
